apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  serviceName: {{ .Values.headless.name }}
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 27017
          args:
            {{- range .Values.extraFlags }}
            - {{ . }}
            {{- end }}
          env:
            - name: MONGODB_ROOT_USERNAME
              value: {{ .Values.auth.rootUser | quote }}
            - name: MONGODB_ROOT_PASSWORD
              value: {{ .Values.auth.rootPassword | quote }}
            - name: MONGODB_REPLICA_SET_MODE
              value: "primary"
            - name: MONGODB_REPLICA_SET_NAME
              value: rs0
          volumeMounts:
            - name: data
              mountPath: /bitnami/mongodb
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-mongodb-0
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
