apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 27017
      nodePort: {{ .Values.service.nodePorts.mongodb }}
  selector:
    app: mongodb
