apiVersion: k3d.io/v1alpha3
kind: Simple
metadata:
  name: local-cluster
servers: 1
agents: 2
ports:
  - port: "80:80@loadbalancer"
  - port: "443:443@loadbalancer"
volumes:
  - volume: /var/lib/docker/volumes/k3d-data:/var/lib/rancher/k3s/storage
registries:
  create:
    name: local-registry
    host: "0.0.0.0"
    hostPort: "5000"
