apiVersion: v2
name: mongodb
description: A Helm chart for Bitnami MongoDB
type: application
version: 0.1.0
appVersion: latest
dependencies:
  - name: mongodb
    version: 14.8.0
    repository: https://charts.bitnami.com/bitnami
