---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  labels:
    app: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017
      name: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32017
      protocol: TCP
      name: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  serviceName: mongodb-headless
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: bitnami/mongodb:7.0.5-debian-11-r13
        ports:
          - containerPort: 27017
            name: mongodb
        env:
          - name: MONGODB_REPLICA_SET_MODE
            value: "primary"
          - name: MONGODB_REPLICA_SET_NAME
            value: "rs0"
          - name: MONGODB_ROOT_USERNAME
            value: "admin"
          - name: MONGODB_ROOT_PASSWORD
            value: "adminPassword"
          - name: MONGODB_USERNAME
            value: "appuser"
          - name: MONGODB_PASSWORD
            value: "appuserPassword"
          - name: MONGODB_DATABASE
            value: "eletricity_usage"
        args:
          - "--bind_ip_all"
        volumeMounts:
          - name: data
            mountPath: /bitnami/mongodb
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: mongodb
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 8Gi
