# Secret：儲存 MongoDB 管理員帳號密碼
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=         # admin (base64)
  mongo-root-password: cGFzc3dvcmQxMjM= # password123 (base64)

---
# ConfigMap：初始化 Replica Set 腳本
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
data:
  init-mongo.js: |
    rs.initiate(
      {
        _id : "rs0",
        members: [
          { _id: 0, host: "mongodb-replica-set-0.mongodb-replica-set:27017" },
          { _id: 1, host: "mongodb-replica-set-1.mongodb-replica-set:27017" },
          { _id: 2, host: "mongodb-replica-set-2.mongodb-replica-set:27017" }
        ]
      }
    )

---
# StatefulSet：部署 MongoDB Replica Set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-replica-set
spec:
  serviceName: "mongodb-replica-set"  # Headless Service 名稱
  replicas: 3
  selector:
    matchLabels:
      app: mongodb-replica-set
  template:
    metadata:
      labels:
        app: mongodb-replica-set
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.14
        args: ["--replSet", "rs0"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-init-scripts
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: MONGO_REPLICA_SET_NAME
          value: rs0
      volumes:
      - name: mongodb-init-scripts
        configMap:
          name: mongodb-init
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi

---
# Headless Service：Pod 內部 DNS 導向
apiVersion: v1
kind: Service
metadata:
  name: mongodb-replica-set
spec:
  clusterIP: None
  selector:
    app: mongodb-replica-set
  ports:
  - port: 27017
    targetPort: 27017

---
# 可選：每個 Pod 建立 LoadBalancer Service，供叢集外部連線（例如 Compass）
apiVersion: v1
kind: Service
metadata:
  name: mongodb-0
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-replica-set-0
  ports:
  - port: 27017
    targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-1
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-replica-set-1
  ports:
  - port: 27017
    targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-2
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-replica-set-2
  ports:
  - port: 27017
    targetPort: 27017

---
# mongo-express：管理介面
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:1.0.2-20-alpine3.19
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_URL
          value: "mongodb://admin:password123@mongodb-replica-set-0.mongodb-replica-set:27017,mongodb-replica-set-1.mongodb-replica-set:27017,mongodb-replica-set-2.mongodb-replica-set:27017/?replicaSet=rs0"
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER_SELECTION_TIMEOUT_MS
          value: "60000"

---
# mongo-express Service：開放對外介面
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  type: LoadBalancer
  selector:
    app: mongo-express
  ports:
  - port: 8081
    targetPort: 8081
