apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://mongodb.github.io/helm-charts
    chart: community-operator
    targetRevision: 0.7.5
    helm:
      values: |
        operator:
          watchedNamespaces: [mongodb]
        featureCompatibilityVersion: "6.0"
        persistent: false
        additionalMongodConfig:
          storage:
            dbPath: /data/db
        credentials:
          root:
            password: "rootPassword"
          user:
            name: admin
            password: "adminPassword"
            database: eletricity_usage
            roles:
              - name: clusterAdmin
                db: admin
              - name: readWrite
                db: eletricity_usage
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
